improvement: Make the demand last transition time and optional parameter
palantir/k8s-spark-scheduler-lib pull request #35
Opened 2020-08-29 15:22 UTC by splucs

## Summary
This is required in order to avoid serialization errors when the parameter is initially not set.
The value "null" that is added when the time is empty is only properly unmarshaled if the field is a pointer. This is the expected way validation works in k8s.

2020-08-31 14:42 UTC, ashrayjain requested changes
There are several examples in k8s where this is not a pointer (and is set to omitempty)
Can you explain why this needs to be a pointer?

```
	// Last time the condition transit from one status to another.
	// +optional
	LastTransitionTime metav1.Time `json:"lastTransitionTime,omitempty"
```
Example from v1.NodeCondition ^^

2020-08-31 15:05 UTC, splucs commented
@ashrayjain I keep getting validation errors when the operator issues the call to the API server with the value unset.
When the value is not set, a string with value "null" is set when marshalling to JSON.
```
// MarshalJSON implements the json.Marshaler interface.
func (t Time) MarshalJSON() ([]byte, error) {
	if t.IsZero() {
		// Encode unset/nil objects as JSON's "null".
		return []byte("null"), nil
	}
	buf := make([]byte, 0, len(time.RFC3339)+2)
	buf = append(buf, '"')
	// time cannot contain non escapable JSON characters
	buf = t.UTC().AppendFormat(buf, time.RFC3339)
	buf = append(buf, '"')
	return buf, nil
}
```
When unmarshaling, if the value is not a pointer it tries to parse the string "null" into a time and gets a validation error. However if the value is a pointer, a JSON unmarshaller override kicks in and processes null correctly.
```
// UnmarshalJSON implements the json.Unmarshaller interface.
func (t *Time) UnmarshalJSON(b []byte) error {
	if len(b) == 4 && string(b) == "null" {
		t.Time = time.Time{}
		return nil
	}

	var str string
	err := json.Unmarshal(b, &str)
	if err != nil {
		return err
	}

	pt, err := time.Parse(time.RFC3339, str)
	if err != nil {
		return err
	}

	t.Time = pt.Local()
	return nil
}
```

2020-09-01 11:04 UTC, ashrayjain commented
```
// UnmarshalJSON implements the json.Unmarshaller interface.
func (t *Time) UnmarshalJSON(b []byte) error {
	if len(b) == 4 && string(b) == "null" {
		t.Time = time.Time{}
		return nil
	}

```
This is the unmarshalling code, so having the string `null` is a-ok for unmarshalling purposes and gives the desired behaviour of empty struct being set?

2020-09-01 18:56 UTC, ashrayjain approved these changes

2020-09-01 19:00 UTC, merged